server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: /h2-console # h2 웹 패스

  datasource:
    driver-class-name: org.h2.Driver # 데이터베이스 프로그램 회사마다 이름이 다름
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password: # 공백이면 비밀번호 없음
    generate-unique-name: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # 데이터베이스마다 쿼리가 조금씩 다름 특정 데이터베이스를 적용하는 설정
    show_sql: true # 쿼리 확인
    properties:
      hibernate:
        format_sql: true # 쿼리가 나올때 정돈되서 나옴